image: mminks/dind-aech:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - run

rspec:
  stage: test
  tags:
    - docker
  script:
    - docker build --tag ci-ampel:latest .
    - docker run ci-ampel:latest bundle exec rspec

ci-ampel:
  stage: run
  tags:
    - docker
  script:
    - docker run -e BASE_URI=${BASE_URI} -e TOKEN=${TOKEN} -e SLACK_HOOK_URI=${SLACK_HOOK_URI} -e SLACK_CHANNEL=${SLACK_CHANNEL} ci-ampel:latest /app/bin/ampel -g -d -s -r
  only:
    refs:
      - master
